### ISSUE TITLE
test pre-header symbol

### ISSUE THREAD

**Issue by zross** [SaraDeLessio/proj-rmarkdown-style#10]
```css
h2:before{
color: #0A2D6D;
padding-right: 0.3em;
margin-left: 0;
content: "///";
}
```
